services:
  api:
    build:
      context: ./back
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:1234@db:3306/planktonsdb
    volumes:
      - ./back:/app
    networks:
      - mynetwork

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "planktonsdb"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 10
      start_period: 30s
    volumes:
      - ./db_scripts_overall:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    environment:
      NEXT_PUBLIC_API_URL: "http://0.0.0.0:8000/"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
