# Generated by Django 5.0.4 on 2024-04-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nutrients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionalNeeds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plankton_id', models.BigIntegerField()),
                ('nutrient_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'nutritional_needs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planktonslibrary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('water_temperature', models.IntegerField(blank=True, null=True)),
                ('bloom_period', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planktonsLibrary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanktonSolutions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('solution_id', models.BigIntegerField()),
                ('plankton_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'plankton_solutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solutions',
                'managed': False,
            },
        ),
    ]
